### ISSUE TITLE
Demo creating new Issues

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/devs-jan-2016#1]
Please leave a comment here!

**Comment by idt911-jmiller** [comment]
First

**Comment by mfunk** [comment]
got it

**Comment by einaooka** [comment]
Hello.

**Comment by Oshuary** [comment]
Jason you beat me!

**Comment by jchou1-uci-edu** [comment]
wee!

**Comment by macdaddyaz** [comment]
Howdy

**Comment by desizombi3** [comment]
'ello

**Comment by ryanrodemoyer** [comment]
3, 2, 1. Go!

**Comment by lucy-uci-edu** [comment]
Hi

**Comment by cody-lny** [comment]
What dis?

**Comment by cshultz-uci** [comment]
tada

**Comment by tlee13enrich** [comment]
Test

**Comment by jaishu** [comment]
Greetings!!
Jai

**Comment by autodesk-delphine** [comment]
Hello world

**Comment by discodan** [comment]
Howdily Hodily

**Comment by zhalimar** [comment]
hi

**Comment by kgonzago** [comment]
hello hello

**Comment by aivatoori** [comment]
cool!

**Comment by topowright-zz** [comment]
Yaeaooooo

**Comment by mdwonchidt911** [comment]
hello

**Comment by dfoll** [comment]
got it

**Comment by mlankford** [comment]
Present

**Comment by Dbarnes1** [comment]
Hello

**Comment by githubteacher** [comment]
:tada: @idt911-jmiller, @mfunk, @einaooka, @Oshuary, @jchou1-uci, @macdaddyaz, @desizombi3, @ryanrodemoyer, @lucyuci, @cody-lny, @ChrisShutlz, @tlee13enrich, @jaishu, @autodesk-delphine, @discodan, @zhalimar, @kgonzago, @aivatoori, @topowright, @mdwonchidt911, @dfoll, @mlankford, and @Dbarnes1 are now  repository collaborators. :balloon:

**Comment by zshah132** [comment]
hi

**Comment by githubteacher** [comment]
:tada: @zshah132 is now a repository collaborator. :balloon:

**Comment by la0ngsuwan** [comment]
Please help me create a branch.

**Comment by githubteacher** [comment]
:tada: @la0ngsuwan is now a repository collaborator. :balloon:

**Comment by jlannan** [comment]
Add me
