### ISSUE TITLE
Can u create an issue for a specific branch?

### ISSUE THREAD

**Issue by zshah132** [githubteacher/devs-jan-2016#32]

**Comment by jaw6** [comment]
No, issues apply to the entire repository, they can't be scoped to a specific branch. Rather, you would open a pull request from a branch, which could then be linked to an issue. Issues indicate "something's wrong here" -- a typo or a bug or something like that -- branches are where changes are made (to fix what's wrong) -- pull requests are where you propose and discuss a specific change.
