### ISSUE TITLE
merge with master workflow

### ISSUE THREAD

**Issue by kgonzago** [githubteacher/devs-jan-2016#35]
Before merging with master, do you need to sync with master (pull from master) before merging with master?

**Comment by jaw6** [comment]
It's not required, unless there are merge conflicts. If the "merge button" is green, it's safe to merge (no conflicts). If the button is greyed out, there are (likely/potential) conflicts, and you'll be required to manage those conflicts _somehow_. Generally, the easiest path to manage conflicts is to pull changes from master and resolve any conflicts, then push to your branch. Typically, doing this will return the merge button to green / ready to go.
