### ISSUE TITLE
Accidently created two user.name

### ISSUE THREAD

**Issue by lucy-uci-edu** [githubteacher/devs-jan-2016#36]
In command line, I created two user.name, how do I go about removing one?

**Comment by jaw6** [comment]
@lucyuci the second one `user.name` will write over the first setting.

**Comment by lucy-uci-edu** [comment]
I got something like this

user.name=lucyuci
user.email=lqzheng@uci.edu
user.name==
core.autocrlf=true

**Comment by jaw6** [comment]
Oh, that's interesting -- looks like git was a bit confusion by an extraneous `=`. The best way to clean this up might be to edit your user's configuration file. Your user configuration file is in your home directory and it's called `.gitconfig` (the "dot" or `.` is required). You could open it in atom like so:

```
atom ~/.gitconfig
```

You can erase the line that begins `username==` there to clean things up.
