### ISSUE TITLE
Where can I find the documentation to set up Git?

### ISSUE THREAD

**Issue by autodesk-delphine** [githubteacher/devs-jan-2016#37]
I need the URL to set up my Git on Windows.

**Comment by jaw6** [comment]
Our slides are [here](https://training.github.com/kit/modules/CONT-CLI-01_Basic-Configuration.html) or you can view our [help documentation here](https://help.github.com/articles/set-up-git/)

**Comment by autodesk-delphine** [comment]
Thank you @jaw6 !
