### ISSUE TITLE
Why I am getting Permission denied with git clone command?

### ISSUE THREAD

**Issue by autodesk-delphine** [githubteacher/devs-jan-2016#38]
![image](https://cloud.githubusercontent.com/assets/15110290/12591049/f53c5bac-c433-11e5-8e7b-4ab04accad81.png)

**Comment by jaw6** [comment]
That's a local permission error -- your user doesn't have permission to write to `C:\Program Files\Git`. You should change directory to a different directory -- it's a little odd to clone into the "program file" folder.  Any other folder will do -- but typically, your user should have a "home directory" where you can store documents and project files. `cd` to that directory and try cloning again.

**Comment by autodesk-delphine** [comment]
Thank you @jaw6 !
