### ISSUE TITLE
Question about githubteacher/devs-jan-2016 path

### ISSUE THREAD

**Issue by zshah132** [githubteacher/devs-jan-2016#4]
Can you please explain again what do you call "githubteacher" in the path. I understand devs-jan-2016 is a name of the repository. 
Do you call "githubteacher" a name of the depot?

thank you.

**Comment by jaw6** [comment]
"githubteacher" is the username of the user account which created and owns the repository. My username is "jaw6", if I had created the repository, the path would be `jaw6/devs-jan-2016`. If you had created the repository, the path would be `zshah132/devs-jan-2016`

**Comment by zshah132** [comment]
thank you.
