### ISSUE TITLE
Is there a way to update git from the git prompt?

### ISSUE THREAD

**Issue by mfunk** [githubteacher/devs-jan-2016#40]
I might be missing something here. Downloaded 'lastest' version from link (https://desktop.github.com/), which is v2.5.3. 

![image](https://cloud.githubusercontent.com/assets/3093182/12591399/72cebf32-c41c-11e5-89b0-0c4103d0b0ca.png)

But open git shell and i'm at 1.9.5
![image](https://cloud.githubusercontent.com/assets/3093182/12591373/53dad796-c41c-11e5-939d-76c1857f6083.png)

???

I can't figure out how to switch out of existing repo in the 'windows' shell prompt

**Comment by shiftkey** [comment]
@mfunk could you tell me what this returns from inside the Git 1.9.5 Shell?

> where git

My gut feeling is that this is something other than our Git Shell environment - maybe the Git Bash shortcut that ships with Git for Windows, judging by the version string.

Do you have the Git Shell shortcut on the desktop? I gather that's what you clicked to get the first screenshot, but here's our icons for reference:

<img width="57" alt="screen shot 2016-01-27 at 5 47 15 am" src="https://cloud.githubusercontent.com/assets/359239/12591779/73b3de1c-c4b9-11e5-9adb-8b8e591c23df.png">

**Comment by mfunk** [comment]
From 1.9.5 prompt:

```
$ where git
C:\Program Files (x86)\Git\bin\git.exe
C:\Program Files (x86)\Git\cmd\git.exe
```

**Comment by mfunk** [comment]
Nothing on desktop. Only GitHub For Windows shell is launched from app:

![image](https://cloud.githubusercontent.com/assets/3093182/12592327/d8234372-c420-11e5-9b54-bdff171e89e5.png)

But that basically means i'm stuck in whatever repo GitHub For Windows is pointing to.

**Comment by jaw6** [comment]
@mfunk it looks to me like you have two different git versions installed, one is in `C:\Program Files (x86)\Git\bin\git.exe` and the other is in `C:\Program Files (x86)\Git\cmd\git.exe` (`bin` vs `cmd`). You could run each one individually to confirm which is the newer one, then delete the older one.

**Comment by shiftkey** [comment]
Cool, we're on the right track. From the Git Shell run this command to reinstall those shortcuts:

> github --reinstall-shortcuts

There's no way to update a previous install of Git for Windows so I'd suggest just uninstalling it to remove any additional confusion. You should see an entry under **Programs and Features** that looks like this:

<img width="629" alt="screen shot 2016-01-27 at 6 09 00 am" src="https://cloud.githubusercontent.com/assets/359239/12592476/80fc9bec-c4bc-11e5-9b6d-36fce7c6810a.png">

Uninstall that.

**Comment by mfunk** [comment]
I think I've got it. Probably going to cleanup and reinstall from scratch just to make sure any duplicate installs are gone. Thanks.
