### ISSUE TITLE
touch command is recongnized ?

### ISSUE THREAD

**Issue by autodesk-delphine** [githubteacher/devs-jan-2016#41]
![image](https://cloud.githubusercontent.com/assets/15110290/12591695/1052e0d4-c437-11e5-8508-da6f23a08caa.png)

**Comment by jaw6** [comment]
`touch` is a command on Linux and Mac, it's not always available on Windows. It just creates an empty file. It seems there are a [couple of alternative commands on Windows](http://superuser.com/questions/10426/windows-equivalent-of-the-linux-command-touch/764716)

**Comment by autodesk-delphine** [comment]
Thanks @jaw6 , I resolved the issue with the **echo** comand here : http://superuser.com/questions/502374/equivalent-of-linux-touch-to-create-an-empty-file-with-powershell
