### ISSUE TITLE
Sublime Editor Not Working

### ISSUE THREAD

**Issue by cody-lny** [githubteacher/devs-jan-2016#42]
I setup core.editor to "subl -n -w" based off of the GitHub guide for setting up editor to Sublime Text 2... When I try to commit I get "subl -n -w: command not found"

**Comment by jaw6** [comment]
Did you [install the `subl` command](http://www.sublimetext.com/docs/3/osx_command_line.html) ?

**Comment by cody-lny** [comment]
@jaw6 are there instructions for Windows Git Bash?

**Comment by jaw6** [comment]
Try: https://scotch.io/tutorials/open-sublime-text-from-the-command-line-using-subl-exe-windows

**Comment by cody-lny** [comment]
@jaw6 Thanks for the link but we are still on version 2 for reasons. Here is a great solution for setting up Sublime Text 2 as your git default editor: http://stackoverflow.com/questions/8951275/how-can-i-make-sublime-text-the-default-editor-for-git

Thanks for your help :+1:
