### ISSUE TITLE
how to track a NEW file so git "commit -a" will work. U just made that comment. 

### ISSUE THREAD

**Issue by zshah132** [githubteacher/devs-jan-2016#57]

**Comment by zshah132** [comment]
hoping to get the answer for this :smile: 
Question
how to track a NEW file so git "commit -a" will work? U just made that comment

**Comment by zshah132** [comment]
for a new file, you will have to do "add" first time so git will know about this file. After that any future changes for that file you can do short cut git commit -a which will do  (add + commit). right ?

**Comment by jaw6** [comment]
You can also do `git add .` ("dot" or period) to add _everything_ in the current directory, but be careful with that one -- if you get into a habit of adding everything in that way, it's easy to wind up accidentally adding things that you didn't intend to add. Most of the time, it's best to list the things you want to add explicitly than using shortcuts like that.
